"""Writes time.com from cases.txt: F$TIME() first and last, as "@@ now", then
per case a "@@ N" line and "[result]" or whatever error DCL prints."""
import pathlib

here = pathlib.Path(__file__).parent
cases = (here / "cases.txt").read_text().splitlines()
now = ['$ WRITE SYS$OUTPUT "@@ now"', '$ WRITE SYS$OUTPUT "[", F$TIME(), "]"']
out = ["$! Generated by gen.py from cases.txt.", "$ SET NOON"] + now
for i, c in enumerate(cases, 1):
    out.append(f'$ WRITE SYS$OUTPUT "@@ {i}"')
    out.append(f'$ WRITE SYS$OUTPUT "[", F$CVTIME({c}), "]"')
(here / "time.com").write_text("\n".join(out + now) + "\n")
