"""Writes cld.com from cases.txt: per case, "@@ command", then what CLIDUMP
prints or the error DCL shows."""
import pathlib

here = pathlib.Path(__file__).parent
cases = (here / "cases.txt").read_text().splitlines()
out = ["$! Generated by gen.py from cases.txt.", "$ SET NOON",
       "$ SET COMMAND VPTEST.CLD"]
for c in cases:
    out.append('$ WRITE SYS$OUTPUT "@@ ' + c.replace('"', '""') + '"')
    out.append("$ " + c)
(here / "cld.com").write_text("\n".join(out) + "\n")
