"""Writes fao.com from cases.txt: per case, a "@@ N" line, then "[result]"
or whatever error DCL prints."""
import pathlib

here = pathlib.Path(__file__).parent
cases = (here / "cases.txt").read_text().splitlines()
out = ["$! Generated by gen.py from cases.txt.", "$ SET NOON"]
for i, c in enumerate(cases, 1):
    out.append(f'$ WRITE SYS$OUTPUT "@@ {i}"')
    out.append(f'$ WRITE SYS$OUTPUT "[", F$FAO({c}), "]"')
(here / "fao.com").write_text("\n".join(out) + "\n")
