"""Writes UTILS.COM: setup.txt makes the files, then for each line of
cases.txt a "@@ command" line, what the command prints, and its $STATUS."""
import pathlib

here = pathlib.Path(__file__).parent
out = ["$! Generated by gen.py from setup.txt and cases.txt.", "$ SET NOON",
       "$ SET DEFAULT [.W]"]
out += (here / "setup.txt").read_text().splitlines()
for c in (here / "cases.txt").read_text().splitlines():
    out.append('$ WRITE SYS$OUTPUT "@@ ' + c.replace('"', '""') + '"')
    out.append("$ " + c)
    out.append('$ WRITE SYS$OUTPUT "status ", F$FAO("!XL", F$INTEGER($STATUS))')
(here / "UTILS.COM").write_text("\n".join(out) + "\n")
