"""Writes sys/SYSMSG/SYSMSG.MSG, vmsport's system messages, from what VMS
printed for every SYSTEM, RMS and CLI code (recorded/sysmsg.log), and
the names of all its facilities (recorded/sysfac.log).

The scan used severity 0, so every message says WARNING here; $GETMSG takes
the severity from the code it is given, so that doesn't show."""
import pathlib, re

here = pathlib.Path(__file__).parent
out = here.parent.parent / "sys/SYSMSG/SYSMSG.MSG"
facilities = {0: "SYSTEM", 1: "RMS", 3: "CLI"}
lines = ["! Generated by fixtures/msg/to_sysmsg.py from what OpenVMS printed.",
         "\t.TITLE\tSYSMSG\tsystem messages", "\t.SEVERITY\tWARNING"]
fac = None
for line in (here / "recorded/sysmsg.log").read_text(encoding="latin-1").splitlines():
    m = re.match(r"([0-9A-F]{8}) %(\w+)-\w-(\w+), (.*)$", line)
    if not m:
        continue
    code = int(m.group(1), 16)
    f, n = code >> 16, (code >> 3) & 0xFFF
    if f != fac:
        fac = f
        lines.append(f"\t.FACILITY\t{facilities[f]},{f} /SYSTEM")
    text = m.group(4)
    delim = "<{}>" if ">" not in text else '"{}"'
    lines.append(f"\t.BASE\t{n}")
    lines.append(f"{m.group(3)}\t{delim.format(text)}")
# Every facility VMS names, so shared messages show the right facility.
lines.append("! Facility names (recorded/sysfac.log)")
for line in (here / "recorded/sysfac.log").read_text().splitlines():
    num, name = line.split()
    if int(num) not in facilities:
        lines.append(f"\t.FACILITY\t{name},{num} /SYSTEM")
out.write_text("\n".join(lines) + "\n")
print(f"{out}: {sum(1 for l in lines if not l.startswith(('!', chr(9))))} messages")
