/* xabdef.h: values recorded on OpenVMS (fixtures/rmsdef), made by to_headers.py. */
#ifndef __XABDEF_LOADED
#define __XABDEF_LOADED 1

#define XAB$C_CXT_VER1 1
#define XAB$C_KEY 21
#define XAB$M_DUP 0x1
#define XAB$M_CHG 0x2
#define XAB$M_NUL 0x4
#define XAB$M_IDX_NCMPR 0x8
#define XAB$M_KEY_NCMPR 0x40
#define XAB$M_DAT_NCMPR 0x80
#define XAB$C_STG 0
#define XAB$C_IN2 1
#define XAB$C_BN2 2
#define XAB$C_IN4 3
#define XAB$C_BN4 4
#define XAB$C_PAC 5
#define XAB$C_IN8 6
#define XAB$C_BN8 7
#define XAB$C_COL 8
#define XAB$C_MAX_ASCEND 8
#define XAB$C_DSTG 32
#define XAB$C_DIN2 33
#define XAB$C_DBN2 34
#define XAB$C_DIN4 35
#define XAB$C_DBN4 36
#define XAB$C_DPAC 37
#define XAB$C_DIN8 38
#define XAB$C_DBN8 39
#define XAB$C_DCOL 40
#define XAB$C_MAXDTP 40
#define XAB$K_KEYLEN_V2 64
#define XAB$C_KEYLEN_V2 64
#define XAB$C_PRG3 3
#define XAB$C_PRG2 2
#define XAB$C_PRG1 1
#define XAB$K_KEYLEN_V4 76
#define XAB$C_KEYLEN_V4 76
#define XAB$K_KEYLEN 100
#define XAB$C_KEYLEN 100
#define XAB$V_DUP 0
#define XAB$V_CHG 1
#define XAB$V_NUL 2
#define XAB$V_IDX_NCMPR 3
#define XAB$V_KEY_NCMPR 6
#define XAB$V_DAT_NCMPR 7
#define XAB$C_ALL 20
#define XAB$M_HRD 0x1
#define XAB$M_ONC 0x2
#define XAB$M_CBT 0x20
#define XAB$M_CTG 0x80
#define XAB$C_ANY 0
#define XAB$C_CYL 1
#define XAB$C_LBN 2
#define XAB$C_VBN 3
#define XAB$C_RFI 4
#define XAB$K_ALLLEN 32
#define XAB$C_ALLLEN 32
#define XAB$V_HRD 0
#define XAB$V_ONC 1
#define XAB$V_CBT 5
#define XAB$V_CTG 7
#define XAB$C_DAT 18
#define XAB$K_DATLEN 84
#define XAB$C_DATLEN 84
#define XAB$K_DATLEN_V2 36
#define XAB$C_DATLEN_V2 36
#define XAB$K_DATLEN_V54 44
#define XAB$C_DATLEN_V54 44
#define XAB$K_DATLEN_PRE_ACCDATES 60
#define XAB$C_DATLEN_PRE_ACCDATES 60
#define XAB$K_DATLEN_POST_ACCDATES 84
#define XAB$C_DATLEN_POST_ACCDATES 84
#define XAB$C_FHC 29
#define XAB$M_FTN 0x1
#define XAB$M_CR 0x2
#define XAB$M_PRN 0x4
#define XAB$M_BLK 0x8
#define XAB$M_GBC_PERCENT 0x1
#define XAB$M_GBC_DEFAULT 0x2
#define XAB$K_FHCLEN 44
#define XAB$C_FHCLEN 44
#define XAB$C_PRO 19
#define XAB$M_NOREAD 0x1
#define XAB$M_NOWRITE 0x2
#define XAB$M_NOEXE 0x4
#define XAB$M_NODEL 0x8
#define XAB$M_PROPAGATE 0x1
#define XAB$K_PROLEN_V3 16
#define XAB$C_PROLEN_V3 16
#define XAB$K_PROLEN 88
#define XAB$C_PROLEN 88
#define XAB$V_SYS 0
#define XAB$S_SYS 4
#define XAB$V_OWN 4
#define XAB$S_OWN 4
#define XAB$V_GRP 8
#define XAB$S_GRP 4
#define XAB$V_WLD 12
#define XAB$S_WLD 4
#define XAB$V_NOREAD 0
#define XAB$V_NOWRITE 1
#define XAB$V_NOEXE 2
#define XAB$V_NODEL 3
#define XAB$V_PROPAGATE 0
#define XAB$V_PROPOGATE 0
#define XAB$C_SUM 22
#define XAB$K_SUMLEN 12
#define XAB$C_SUMLEN 12
#define XAB$C_RDT 30
#define XAB$K_RDTLEN 20
#define XAB$C_RDTLEN 20

#endif
