"""Writes sys/SYSMSG/TPU.MSG, TPU's (1010) and EVE's (548) messages, from
what VMS printed for every code (recorded/messages.log, messages.dcl).

The scan used severity 0, so a message's severity is WARNING here unless
VMS returned its code (SEVERITY below)."""
import pathlib, re

here = pathlib.Path(__file__).parent
out = here.parent.parent / "sys/SYSMSG/TPU.MSG"
# Statuses EVE left in $STATUS (recorded/batch.log, recorded/messages.log).
SEVERITY = {0x13F2AF01: "SUCCESS", 0x13F2AF59: "SUCCESS", 0x13F2ED7C: "FATAL"}
known = {c & 0xFFFFFF8: s for c, s in SEVERITY.items()}
names = {548: "EVE", 1010: "TPU"}
seen = {}
for line in (here / "recorded/messages.log").read_text(encoding="latin-1").splitlines():
    m = re.match(r"([0-9A-F]{8}) %(\w+)-\w-(\w+), (.*)$", line.rstrip("\r"))
    if m:
        seen.setdefault(int(m.group(1), 16), (m.group(3), m.group(4)))
lines = ["! Generated by fixtures/eve/to_msg.py from what OpenVMS printed.",
         "\t.TITLE\tTPU\tTPU and EVE messages"]
fac = sev = None
for code, (name, text) in sorted(seen.items()):
    f, n = code >> 16, (code >> 3) & 0xFFF
    if f != fac:
        fac = f
        lines.append(f"\t.FACILITY\t{names[f]},{f} /SYSTEM")
    s = known.get(code & 0xFFFFFF8, "WARNING")
    if s != sev:
        sev = s
        lines.append(f"\t.SEVERITY\t{s}")
    delim = "<{}>" if ">" not in text else '"{}"'
    lines += [f"\t.BASE\t{n}", f"{name}\t{delim.format(text)}"]
out.write_text("\n".join(lines) + "\n")
print(f"{out}: {len(seen)} messages")
